const addonTypes = {
   ADD_ADDON_REQUEST: "ADD_ADDON_REQUEST",
   ADD_ADDON_SUCCESS: "ADD_ADDON_SUCCESS",
   ADD_ADDON_FAILURE: "ADD_ADDON_FAILURE",

   GET_ADDONS_REQUEST: "GET_ADDONS_REQUEST",
   GET_ADDONS_SUCCESS: "GET_ADDONS_SUCCESS",
   GET_ADDONS_FAILURE: "GET_ADDONS_FAILURE",

   UPDATE_ADDON_REQUEST: "UPDATE_ADDON_REQUEST",
   UPDATE_ADDON_SUCCESS: "UPDATE_ADDON_SUCCESS",
   UPDATE_ADDON_FAILURE: "UPDATE_ADDON_FAILURE",

   DELETE_ADDON_REQUEST: "DELETE_ADDON_REQUEST",
   DELETE_ADDON_SUCCESS: "DELETE_ADDON_SUCCESS",
   DELETE_ADDON_FAILURE: "DELETE_ADDON_FAILURE",
};

export default addonTypes;
