// bannerActionTypes.js
export const ADD_BANNER = 'ADD_BANNER';
export const ADD_BANNER_SUCCESS = 'ADD_BANNER_SUCCESS';
export const ADD_BANNER_FAILURE = 'ADD_BANNER_FAILURE';

export const GET_BANNERS = 'GET_BANNERS';
export const GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS';
export const GET_BANNERS_FAILURE = 'GET_BANNERS_FAILURE';

export const UPDATE_BANNER = 'UPDATE_BANNER';
export const UPDATE_BANNER_SUCCESS = 'UPDATE_BANNER_SUCCESS';
export const UPDATE_BANNER_FAILURE = 'UPDATE_BANNER_FAILURE';

export const DELETE_BANNER = 'DELETE_BANNER';
export const DELETE_BANNER_SUCCESS = 'DELETE_BANNER_SUCCESS';
export const DELETE_BANNER_FAILURE = 'DELETE_BANNER_FAILURE';

export const UPDATE_BANNER_STATUS = 'UPDATE_BANNER_STATUS';
export const UPDATE_BANNER_STATUS_SUCCESS = 'UPDATE_BANNER_STATUS_SUCCESS';
export const UPDATE_BANNER_STATUS_FAILURE = 'UPDATE_BANNER_STATUS_FAILURE';
