const bannerTypes = {
   ADD_BANNER_REQUEST: 'ADD_BANNER_REQUEST',
   ADD_BANNER_SUCCESS: 'ADD_BANNER_SUCCESS',
   ADD_BANNER_FAILURE: 'ADD_BANNER_FAILURE',

   GET_BANNERS_REQUEST: 'GET_BANNERS_REQUEST',
   GET_BANNERS_SUCCESS: 'GET_BANNERS_SUCCESS',
   GET_BANNERS_FAILURE: 'GET_BANNERS_FAILURE',

   UPDATE_BANNER_REQUEST: 'UPDATE_BANNER_REQUEST',
   UPDATE_BANNER_SUCCESS: 'UPDATE_BANNER_SUCCESS',
   UPDATE_BANNER_FAILURE: 'UPDATE_BANNER_FAILURE',

   DELETE_BANNER_REQUEST: 'DELETE_BANNER_REQUEST',
   DELETE_BANNER_SUCCESS: 'DELETE_BANNER_SUCCESS',
   DELETE_BANNER_FAILURE: 'DELETE_BANNER_FAILURE',
};

export default bannerTypes;
