// screenActionTypes.js
export const ADD_SCREEN = 'ADD_SCREEN';
export const ADD_SCREEN_SUCCESS = 'ADD_SCREEN_SUCCESS';
export const ADD_SCREEN_FAILURE = 'ADD_SCREEN_FAILURE';

export const GET_SCREENS = 'GET_SCREENS';
export const GET_SCREENS_SUCCESS = 'GET_SCREENS_SUCCESS';
export const GET_SCREENS_FAILURE = 'GET_SCREENS_FAILURE';

export const UPDATE_SCREEN = 'UPDATE_SCREEN';
export const UPDATE_SCREEN_SUCCESS = 'UPDATE_SCREEN_SUCCESS';
export const UPDATE_SCREEN_FAILURE = 'UPDATE_SCREEN_FAILURE';

export const DELETE_SCREEN = 'DELETE_SCREEN';
export const DELETE_SCREEN_SUCCESS = 'DELETE_SCREEN_SUCCESS';
export const DELETE_SCREEN_FAILURE = 'DELETE_SCREEN_FAILURE';

export const UPDATE_SCREEN_STATUS = 'UPDATE_SCREEN_STATUS';
export const UPDATE_SCREEN_STATUS_SUCCESS = 'UPDATE_SCREEN_STATUS_SUCCESS';
export const UPDATE_SCREEN_STATUS_FAILURE = 'UPDATE_SCREEN_STATUS_FAILURE';
