const screenTypes = {
   ADD_SCREEN_REQUEST: 'ADD_SCREEN_REQUEST',
   ADD_SCREEN_SUCCESS: 'ADD_SCREEN_SUCCESS',
   ADD_SCREEN_FAILURE: 'ADD_SCREEN_FAILURE',

   GET_SCREENS_REQUEST: 'GET_SCREENS_REQUEST',
   GET_SCREENS_SUCCESS: 'GET_SCREENS_SUCCESS',
   GET_SCREENS_FAILURE: 'GET_SCREENS_FAILURE',

   UPDATE_SCREEN_REQUEST: 'UPDATE_SCREEN_REQUEST',
   UPDATE_SCREEN_SUCCESS: 'UPDATE_SCREEN_SUCCESS',
   UPDATE_SCREEN_FAILURE: 'UPDATE_SCREEN_FAILURE',

   DELETE_SCREEN_REQUEST: 'DELETE_SCREEN_REQUEST',
   DELETE_SCREEN_SUCCESS: 'DELETE_SCREEN_SUCCESS',
   DELETE_SCREEN_FAILURE: 'DELETE_SCREEN_FAILURE',
};

export default screenTypes;
