const cakeTypes = {
   ADD_CAKE_REQUEST: "ADD_CAKE_REQUEST",
   ADD_CAKE_SUCCESS: "ADD_CAKE_SUCCESS",
   ADD_CAKE_FAILURE: "ADD_CAKE_FAILURE",

   GET_CAKES_REQUEST: "GET_CAKES_REQUEST",
   GET_CAKES_SUCCESS: "GET_CAKES_SUCCESS",
   GET_CAKES_FAILURE: "GET_CAKES_FAILURE",

   UPDATE_CAKE_REQUEST: "UPDATE_CAKE_REQUEST",
   UPDATE_CAKE_SUCCESS: "UPDATE_CAKE_SUCCESS",
   UPDATE_CAKE_FAILURE: "UPDATE_CAKE_FAILURE",

   DELETE_CAKE_REQUEST: "DELETE_CAKE_REQUEST",
   DELETE_CAKE_SUCCESS: "DELETE_CAKE_SUCCESS",
   DELETE_CAKE_FAILURE: "DELETE_CAKE_FAILURE",
};

export default cakeTypes;
