const giftTypes = {
   ADD_GIFT_REQUEST: "ADD_GIFT_REQUEST",
   ADD_GIFT_SUCCESS: "ADD_GIFT_SUCCESS",
   ADD_GIFT_FAILURE: "ADD_GIFT_FAILURE",

   GET_GIFTS_REQUEST: "GET_GIFTS_REQUEST",
   GET_GIFTS_SUCCESS: "GET_GIFTS_SUCCESS",
   GET_GIFTS_FAILURE: "GET_GIFTS_FAILURE",

   UPDATE_GIFT_REQUEST: "UPDATE_GIFT_REQUEST",
   UPDATE_GIFT_SUCCESS: "UPDATE_GIFT_SUCCESS",
   UPDATE_GIFT_FAILURE: "UPDATE_GIFT_FAILURE",

   DELETE_GIFT_REQUEST: "DELETE_GIFT_REQUEST",
   DELETE_GIFT_SUCCESS: "DELETE_GIFT_SUCCESS",
   DELETE_GIFT_FAILURE: "DELETE_GIFT_FAILURE",
};

export default giftTypes;
