const customerTypes = {
   GET_CUSTOMERS_REQUEST: 'GET_CUSTOMERS_REQUEST',
   GET_CUSTOMERS_SUCCESS: 'GET_CUSTOMERS_SUCCESS',
   GET_CUSTOMERS_FAILURE: 'GET_CUSTOMERS_FAILURE',
};

export default customerTypes;