const customerBookingActionTypes = {

   SET_BOOKING_DATA: "SET_BOOKING_DATA",

   SET_BOOKING_CITY: "SET_CUSTOMER_CITY",

   SET_BOOKING_LOCATION: "SET_CUSTOMER_LOCATION",

   SET_BOOKING_SCREEN: "SET_CUSTOMER_SCREEN",

   SET_BOOKING_DATE: "SET_BOOKING_DATE",

   SET_BOOKING_SLOT: "SET_BOOKING_SLOT",

   SET_BOOKING_PACKAGE: "SET_BOOKING_PACKAGE"

}

export default customerBookingActionTypes