const customerBookingActionTypes = {

   SET_CUSTOMER_BOOKING:'SET_CUSTOMER_BOOKING',

   SET_BOOKING_DATA: "SET_BOOKING_DATA",

   SET_BOOKING_CITY: "SET_CUSTOMER_CITY",

   SET_BOOKING_LOCATION: "SET_CUSTOMER_LOCATION",

   SET_BOOKING_SCREEN: "SET_CUSTOMER_SCREEN",

   SET_BOOKING_DATE: "SET_BOOKING_DATE",

   SET_BOOKING_SLOT: "SET_BOOKING_SLOT",

   SET_BOOKING_PACKAGE: "SET_BOOKING_PACKAGE",

   SET_BOOKING_OCCASION: "SET_BOOKING_OCCASION",

   SET_BOOKING_ADDONS: "SET_BOOKING_ADDONS",

   SET_BOOKING_GIFTS: "SET_BOOKING_GIFTS",

   SET_BOOKING_CAKES: "SET_BOOKING_CAKES",

   SET_BOOKING_CUSTOMER: 'SET_BOOKING_CUSTOMER',

   SET_BOOKING_TOTAL: 'SET_BOOKING_TOTAL',

   SET_BOOKING_OTHERINFO: 'SET_BOOKING_OTHERINFO',

   SET_BOOKING_ADVANCE: 'SET_BOOKING_ADVANCE',

   SET_BOOKING_NOTE: 'SET_BOOKING_NOTE',

   // SET_BOOKING_SPECIALDISCOUNT:"SET_BOOKING_SPECIALDISCOUNT",

   SET_BOOKING_FULLPAYMENT:'SET_BOOKING_FULLPAYMENT'

}

export default customerBookingActionTypes