const authTypes = {
   LOGIN_REQUEST: 'LOGIN_REQUEST',
   LOGIN_SUCCESS: 'LOGIN_SUCCESS',
   LOGIN_FAILURE: 'LOGIN_FAILURE',

   REG_REQUEST: 'REG_REQUEST',
   REG_SUCCESS: 'REG_SUCCESS',
   REG_FAILURE: 'REG_FAILURE',

   INITIAL_LOGIN_REQUEST: 'INITIAL_LOGIN_REQUEST',
   INITIAL_LOGIN_SUCCESS: 'INITIAL_LOGIN_SUCCESS',
   INITIAL_LOGIN_FAILURE: 'INITIAL_LOGIN_FAILURE',

   LOGOUT: 'LOGOUT',
};

export default authTypes;