const cityTypes = {
   ADD_CITY_REQUEST: 'ADD_CITY_REQUEST',
   ADD_CITY_SUCCESS: 'ADD_CITY_SUCCESS',
   ADD_CITY_FAILURE: 'ADD_CITY_FAILURE',

   GET_CITIES_REQUEST: 'GET_CITIES_REQUEST',
   GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',
   GET_CITIES_FAILURE: 'GET_CITIES_FAILURE',

   UPDATE_CITY_REQUEST: 'UPDATE_CITY_REQUEST',
   UPDATE_CITY_SUCCESS: 'UPDATE_CITY_SUCCESS',
   UPDATE_CITY_FAILURE: 'UPDATE_CITY_FAILURE',

   DELETE_CITY_REQUEST: 'DELETE_CITY_REQUEST',
   DELETE_CITY_SUCCESS: 'DELETE_CITY_SUCCESS',
   DELETE_CITY_FAILURE: 'DELETE_CITY_FAILURE',
};

export default cityTypes;
