const bookingTypes = {

   GET_BOOKINGS_REQUEST: 'GET_BOOKINGS_REQUEST',
   GET_BOOKINGS_SUCCESS: 'GET_BOOKINGS_SUCCESS',
   GET_BOOKINGS_FAILURE: 'GET_BOOKINGS_FAILURE',

   GET_BOOKING_REQUEST: 'GET_BOOKING_REQUEST',
   GET_BOOKING_SUCCESS: 'GET_BOOKING_SUCCESS',
   GET_BOOKING_FAILURE: 'GET_BOOKING_FAILURE',

   CREATE_BOOKING_REQUEST: 'CREATE_BOOKING_REQUEST',
   CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
   CREATE_BOOKING_FAILURE: 'CREATE_BOOKING_FAILURE',

};

export default bookingTypes;