const couponTypes = {
   ADD_COUPON_REQUEST: 'ADD_COUPON_REQUEST',
   ADD_COUPON_SUCCESS: 'ADD_COUPON_SUCCESS',
   ADD_COUPON_FAILURE: 'ADD_COUPON_FAILURE',

   GET_COUPONS_REQUEST: 'GET_COUPONS_REQUEST',
   GET_COUPONS_SUCCESS: 'GET_COUPONS_SUCCESS',
   GET_COUPONS_FAILURE: 'GET_COUPONS_FAILURE',

   UPDATE_COUPON_REQUEST: 'UPDATE_COUPON_REQUEST',
   UPDATE_COUPON_SUCCESS: 'UPDATE_COUPON_SUCCESS',
   UPDATE_COUPON_FAILURE: 'UPDATE_COUPON_FAILURE',

   DELETE_COUPON_REQUEST: 'DELETE_COUPON_REQUEST',
   DELETE_COUPON_SUCCESS: 'DELETE_COUPON_SUCCESS',
   DELETE_COUPON_FAILURE: 'DELETE_COUPON_FAILURE',
};

export default couponTypes;
