const locationTypes = {
   ADD_LOCATION_REQUEST: 'ADD_LOCATION_REQUEST',
   ADD_LOCATION_SUCCESS: 'ADD_LOCATION_SUCCESS',
   ADD_LOCATION_FAILURE: 'ADD_LOCATION_FAILURE',

   GET_LOCATIONS_REQUEST: 'GET_LOCATIONS_REQUEST',
   GET_LOCATIONS_SUCCESS: 'GET_LOCATIONS_SUCCESS',
   GET_LOCATIONS_FAILURE: 'GET_LOCATIONS_FAILURE',

   GET_LOCATION_REQUEST: 'GET_LOCATION_REQUEST',
   GET_LOCATION_SUCCESS: 'GET_LOCATION_SUCCESS',
   GET_LOCATION_FAILURE: 'GET_LOCATION_FAILURE',

   UPDATE_LOCATION_REQUEST: 'UPDATE_LOCATION_REQUEST',
   UPDATE_LOCATION_SUCCESS: 'UPDATE_LOCATION_SUCCESS',
   UPDATE_LOCATION_FAILURE: 'UPDATE_LOCATION_FAILURE',

   DELETE_LOCATION_REQUEST: 'DELETE_LOCATION_REQUEST',
   DELETE_LOCATION_SUCCESS: 'DELETE_LOCATION_SUCCESS',
   DELETE_LOCATION_FAILURE: 'DELETE_LOCATION_FAILURE',
};

export default locationTypes;
