const occasionTypes = {
   ADD_OCCASION_REQUEST: "ADD_OCCASION_REQUEST",
   ADD_OCCASION_SUCCESS: "ADD_OCCASION_SUCCESS",
   ADD_OCCASION_FAILURE: "ADD_OCCASION_FAILURE",

   GET_OCCASIONS_REQUEST: "GET_OCCASIONS_REQUEST",
   GET_OCCASIONS_SUCCESS: "GET_OCCASIONS_SUCCESS",
   GET_OCCASIONS_FAILURE: "GET_OCCASIONS_FAILURE",

   UPDATE_OCCASION_REQUEST: "UPDATE_OCCASION_REQUEST",
   UPDATE_OCCASION_SUCCESS: "UPDATE_OCCASION_SUCCESS",
   UPDATE_OCCASION_FAILURE: "UPDATE_OCCASION_FAILURE",

   DELETE_OCCASION_REQUEST: "DELETE_OCCASION_REQUEST",
   DELETE_OCCASION_SUCCESS: "DELETE_OCCASION_SUCCESS",
   DELETE_OCCASION_FAILURE: "DELETE_OCCASION_FAILURE",
};

export default occasionTypes;
